services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d